baseURL = ""
title = "Boutique Yloy"
author = "Rycko"
theme = "simple-snipcart-shop"
contentDir = "products"
[params]
  instagram = "boutique_yloy"
  facebook = "boutiqueyloy"
  header = "Bienvenido a Boutique Yloy!"
  description = "Accesorios útiles, comodos y bonitos"
  products_title = "Nuestros productos"
  reviews_title = "Nuestras recomendaciones"
  not_found = "Lo sentimos no tenemos productos en esta categoria."
  categories = [
    "For you",
    "For the home",
    "For the friends"
  ]
  collage = [
    "/images/collage-1.jpg",
    "/images/collage-2.jpg",
    "/images/collage-3.jpg",
    "/images/collage-8.jpg",
    "/images/collage-7.png",
    "/images/collage-4.jpg",
    "/images/collage-5.jpg",
    "/images/collage-6.jpg"
  ]
  # snipcart features will not work without an api key
  # see https://docs.snipcart.com/v3/dashboard/account-configuration#3-api-keys
  snipcart_key = "OWFkNDI4MGItNGUxYS00MGZkLWIwNzAtODQ0NWY3MjZiNGFjNjM3OTYyMjU4NDY2NDExMzM1"
  favicon= "/images/favicon.png"

